# Generated by Django 4.2.7 on 2023-12-04 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SatData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mission', models.CharField(max_length=50)),
                ('product_type', models.CharField(max_length=50)),
                ('directory_path', models.CharField(max_length=255)),
                ('metadata_path', models.CharField(max_length=255)),
                ('thumbnail_path', models.CharField(max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sat_data',
            },
        ),
        migrations.CreateModel(
            name='ImageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_type', models.CharField(max_length=20)),
                ('img_path', models.CharField(max_length=255)),
                ('archived_img_paths', models.TextField()),
                ('sat_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sat_data.satdata')),
            ],
            options={
                'db_table': 'image_info',
            },
        ),
        migrations.CreateModel(
            name='CaptureInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_start_time', models.DateTimeField()),
                ('product_stop_time', models.DateTimeField()),
                ('product_type', models.CharField(max_length=50)),
                ('sat_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sat_data.satdata')),
            ],
            options={
                'db_table': 'capture_info',
            },
        ),
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=50)),
                ('sat_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sat_data.satdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'calculation',
            },
        ),
        migrations.CreateModel(
            name='BoundLatitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('north', models.FloatField()),
                ('east', models.FloatField()),
                ('south', models.FloatField()),
                ('west', models.FloatField()),
                ('sat_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sat_data.satdata')),
            ],
            options={
                'db_table': 'bound_latitudes',
            },
        ),
        migrations.CreateModel(
            name='AreaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=20)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('capture_time', models.DateTimeField(null=True)),
                ('sat_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sat_data.satdata')),
            ],
            options={
                'db_table': 'area_info',
            },
        ),
    ]
