# Generated by Django 5.0 on 2024-04-08 15:43

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
import sat_data.models
import utils.services.overwrite_storage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SatData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='No name', max_length=255)),
                ('mission', models.CharField(blank=True, default='unknown', max_length=50, verbose_name='Mission')),
                ('product_type', models.CharField(blank=True, default='unknown', max_length=50, verbose_name='Product Type')),
                ('extracted_path', models.CharField(blank=True, max_length=255, verbose_name='Extracted Path')),
                ('band_tables', models.JSONField(blank=True, max_length=2000, null=True, verbose_name='Band Tables')),
                ('processing_done', models.BooleanField(blank=True, default=False, null=True, verbose_name='Processing Done')),
                ('archive', models.FileField(blank=True, max_length=255, null=True, storage=utils.services.overwrite_storage.OverwriteStorage(), upload_to=sat_data.models.archive_upload_path, verbose_name='Archive')),
                ('mtd', models.FileField(blank=True, max_length=255, null=True, storage=utils.services.overwrite_storage.OverwriteStorage(), upload_to=sat_data.models.metadata_upload_path, verbose_name='MTD')),
                ('manifest', models.FileField(blank=True, max_length=255, null=True, storage=utils.services.overwrite_storage.OverwriteStorage(), upload_to=sat_data.models.metadata_upload_path, verbose_name='Manifest')),
                ('eop_metadata', models.FileField(blank=True, max_length=255, null=True, storage=utils.services.overwrite_storage.OverwriteStorage(), upload_to=sat_data.models.metadata_upload_path, verbose_name='EOP Metadata')),
                ('xfdu_manifest', models.FileField(blank=True, max_length=255, null=True, storage=utils.services.overwrite_storage.OverwriteStorage(), upload_to=sat_data.models.metadata_upload_path, verbose_name='Xfdu Manifest')),
                ('inspire', models.FileField(blank=True, max_length=255, null=True, storage=utils.services.overwrite_storage.OverwriteStorage(), upload_to=sat_data.models.metadata_upload_path, verbose_name='Inspire')),
                ('thumbnail', models.ImageField(blank=True, max_length=255, null=True, storage=utils.services.overwrite_storage.OverwriteStorage(), upload_to=sat_data.models.thumbnail_upload_path, verbose_name='Thumbnail')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('coordinates', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326, verbose_name='Polygon Coordinates')),
                ('leaflet_coordinates', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326, verbose_name='Leaflet Coordinates')),
                ('user', models.ForeignKey(blank=True, default=sat_data.models.get_dews_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sat_datas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sat_data',
                'ordering': ['-creation_time'],
            },
        ),
        migrations.CreateModel(
            name='TimeTravel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No name', max_length=100, verbose_name='Name')),
                ('mission', models.CharField(blank=True, default='unknown', max_length=50, verbose_name='Mission')),
                ('thumbnail', models.ImageField(blank=True, max_length=255, null=True, storage=utils.services.overwrite_storage.OverwriteStorage(), upload_to='time_travel/<django.db.models.fields.CharField>/<django.db.models.fields.UUIDField>/thumbnail', verbose_name='Thumbnail')),
                ('coordinates', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326, verbose_name='Polygon Coordinates')),
                ('leaflet_coordinates', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326, verbose_name='Leaflet Coordinates')),
                ('product_type', models.CharField(blank=True, default='unknown', max_length=50, verbose_name='Product Type')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('stop_time', models.DateTimeField(blank=True, null=True)),
                ('sat_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='area', serialize=False, to='sat_data.satdata')),
            ],
            options={
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range', models.IntegerField(blank=True, default=10, help_text='One pixel in meter')),
                ('type', models.CharField(blank=True, max_length=50, verbose_name='Type')),
                ('raster', django.contrib.gis.db.models.fields.RasterField(blank=True, null=True, srid=4326, verbose_name='Raster')),
                ('srid', models.IntegerField(blank=True, default=4326, verbose_name='SRID')),
                ('band_file', models.FileField(blank=True, max_length=255, upload_to=sat_data.models.band_upload_path, verbose_name='Band file')),
                ('sat_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='sat_data.satdata')),
            ],
            options={
                'db_table': 'band',
            },
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx_type', models.CharField(max_length=20)),
                ('img', models.ImageField(blank=True, max_length=255, null=True, storage=utils.services.overwrite_storage.OverwriteStorage(), upload_to=sat_data.models.index_upload_path, verbose_name='Index img')),
                ('archived_img_paths', models.TextField()),
                ('sat_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index', to='sat_data.satdata')),
            ],
            options={
                'db_table': 'index',
            },
        ),
        migrations.CreateModel(
            name='SHRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.CharField(max_length=50)),
                ('bands', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), default=list, size=None)),
                ('resolution', models.IntegerField()),
                ('metrics_to_calc', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), default=list, size=None)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('coordinates', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326, verbose_name='Polygon Coordinates')),
                ('progress', models.CharField(blank=True, default='in progress', max_length=20)),
                ('user', models.ForeignKey(blank=True, default=sat_data.models.get_dews_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sh_request',
                'ordering': ['-creation_time'],
            },
        ),
        migrations.AddField(
            model_name='satdata',
            name='sh_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sat_datas', to='sat_data.shrequest'),
        ),
        migrations.AddField(
            model_name='satdata',
            name='time_travel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sat_datas', to='sat_data.timetravel'),
        ),
    ]
