# Generated by Django 5.0 on 2024-04-05 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shrequest',
            name='sat_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sh_request', to='sat_data.satdata'),
        ),
    ]
