# Generated by Django 5.0 on 2024-03-29 13:13

import sat_data.models
import utils.services.overwrite_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satdata',
            name='archive',
            field=models.FileField(blank=True, max_length=255, null=True, storage=utils.services.overwrite_storage.OverwriteStorage(), upload_to=sat_data.models.archive_upload_path, verbose_name='Archive'),
        ),
    ]
