# Generated by Django 4.2.7 on 2023-12-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satdata',
            name='metadata_path',
        ),
        migrations.RemoveField(
            model_name='satdata',
            name='thumbnail_path',
        ),
        migrations.AddField(
            model_name='satdata',
            name='metadata',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='satdata',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
