# Generated by Django 5.0 on 2023-12-07 06:52

import sat_data.enums.satellite_mission
import sat_data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat_data', '0002_remove_satdata_metadata_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satdata',
            name='metadata',
            field=models.FileField(blank=True, null=True, upload_to=sat_data.models.metadata_upload_path),
        ),
        migrations.AlterField(
            model_name='satdata',
            name='mission',
            field=models.CharField(choices=sat_data.enums.satellite_mission.SatelliteMission.as_tuple, max_length=50),
        ),
        migrations.AlterField(
            model_name='satdata',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=sat_data.models.thumbnail_upload_path),
        ),
    ]
