# Generated by Django 5.0 on 2024-03-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat_data', '0002_alter_satdata_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='satdata',
            name='bands',
            field=models.JSONField(blank=True, default=list, max_length=2000, null=True, verbose_name='Bands'),
        ),
    ]
