# Generated by Django 5.0 on 2023-12-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat_data', '0002_alter_satdata_archive_alter_satdata_metadata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satdata',
            name='directory_path',
        ),
        migrations.AddField(
            model_name='satdata',
            name='extracted_path',
            field=models.CharField(blank=True, max_length=255, verbose_name='Extracted Path'),
        ),
    ]
