# Generated by Django 5.0 on 2023-12-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat_data', '0002_remove_satdata_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='satdata',
            name='name',
            field=models.CharField(blank=True, default='No name', max_length=255),
        ),
    ]
