# Generated by Django 5.0 on 2023-12-11 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sat_data', '0003_remove_satdata_directory_path_satdata_extracted_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='satdata',
            options={'ordering': ['-creation_time']},
        ),
    ]
