# Generated by Django 5.0 on 2024-04-03 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sat_data', '0003_satdata_bands'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='band_path',
        ),
    ]
