# Generated by Django 5.0 on 2024-04-03 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat_data', '0004_remove_band_band_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satdata',
            name='bands',
        ),
        migrations.AlterField(
            model_name='band',
            name='sat_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='sat_data.satdata'),
        ),
    ]
