# Generated by Django 5.0 on 2023-12-11 15:30

import sat_data.models
import utils.overwrite_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat_data', '0004_alter_satdata_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satdata',
            name='archive',
            field=models.FileField(storage=utils.overwrite_storage.OverwriteStorage(), upload_to=sat_data.models.archive_upload_path, verbose_name='Archive'),
        ),
        migrations.AlterField(
            model_name='satdata',
            name='metadata',
            field=models.FileField(blank=True, null=True, storage=utils.overwrite_storage.OverwriteStorage(), upload_to=sat_data.models.metadata_upload_path, verbose_name='Metadata'),
        ),
        migrations.AlterField(
            model_name='satdata',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=utils.overwrite_storage.OverwriteStorage(), upload_to=sat_data.models.thumbnail_upload_path, verbose_name='Thumbnail'),
        ),
    ]
