version: '3'

services:
  dews:
    image: dews:latest
    container_name: dews
    build:
      context: .
    working_dir: /app/dews
    volumes:
      - ./dews/:/app/dews/ # for development purposes
      - ./dews/django.log:/app/dews/django.log
      - static:/dews/static # "static" is a Docker volume
      - media:/dews/media # "media" is a Docker volume
    env_file:
      - .env
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - dews-db

  nginx:
    container_name: dews-nginx
    build: ./nginx
    volumes: 
      - static:/static # "static" is a Docker volume
      - media:/media # "media" is a Docker volume
    ports:
      - "80:80"
    depends_on:
      - dews

  dews-db:
    image: postgis/postgis:latest
    container_name: dews-db
    environment:
      POSTGRES_DB: dews
      POSTGRES_USER: dews
      POSTGRES_PASSWORD: dews
      PGDATA: /var/lib/postgresql/data/pgdat
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  static:
  media: