version: '3'

services:
  dews:
    image: dews:latest
    container_name: dews
    networks:
      dews-network:
        ipv4_address: 172.19.0.2
    build:
      context: .
      dockerfile: docker/backend/Dockerfile.python
    working_dir: /app/backend
    # command: python /app/backend/main.py
    # command: /bin/sh -c "flask run --host=0.0.0.0 && python main.py"
    command: flask run --host=0.0.0.0
    volumes:
      - ./backend:/app/backend # for development purposes
      - ./dropzone:/app/dropzone
      # - ./backend/backend.log:/app/backend/backend.log
      # - ./backend/files:/app/backend/files
    ports:
      - "5000:5000"

  dews-db:
    image: postgis/postgis:14-3.3
    container_name: dews-db
    networks:
      dews-network:
        ipv4_address: 172.19.0.3
    environment:
      POSTGRES_DB: dews
      POSTGRES_USER: dews
      POSTGRES_PASSWORD: dews
      PGDATA: /var/lib/postgresql/data/pgdat
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  # frontend:
  #   image: dews-frontend:latest
  #   container_name: dews-frontend
  #   networks:
  #     dews-network:
  #       ipv4_address: 172.19.0.4
  #   build:
  #     context: .
  #     dockerfile: docker/frontend/Dockerfile.flutter
  #   working_dir: /app/frontend
  #   command: "flutter run -d web-server --web-hostname 0.0.0.0 --web-port 80"
  #   ports:
  #     - "80:80" 


networks:
  dews-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: dews-bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
