version: '3'

services:
  dews:
    image: dews:latest
    container_name: dews
    build:
      context: .
    working_dir: /app/dews
    volumes:
      - ./dews/:/app/dews/ # for development purposes
      - static:/dews/static # "static" is a Docker volume
      - ./media:/dews/media # "media" is a Docker volume (TODO: remove "./" in production)
    env_file:
      - .env
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - dews-db

  nginx:
    container_name: dews-nginx
    build: ./nginx
    volumes: 
      - static:/static # "static" is a Docker volume
      - ./media:/media # "media" is a Docker volume (TODO: remove "./" in production)
    ports:
      - "80:80"
    depends_on:
      - dews

  dews-db:
    image: postgis/postgis:latest
    container_name: dews-db
    environment:
      POSTGRES_DB: dews
      POSTGRES_USER: dews
      POSTGRES_PASSWORD: dews
      PGDATA: /var/lib/postgresql/data/pgdat
    ports:
      - 5432:5432
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
      - ./pgdata:/var/lib/postgresql/datar

  dews-db-gui:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: dews@dews.de
      PGADMIN_DEFAULT_PASSWORD: dews
    ports:
      - 5050:80
    depends_on:
      - dews-db


volumes:
  static:
#  media: # TODO: uncomment in production/comment in development