apiVersion: apps/v1
kind: Deployment
metadata:
  name: dews-nginx
  namespace: dews
  labels:
    service: dews-nginx
spec:
  selector:
    matchLabels:
      service: dews-nginx
  template:
    metadata:
      labels:
        service: dews-nginx
    spec:
      containers:
      - image: git.haw-hamburg.de:5000/wja999/dews-nginx
        name: dews-nginx
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: static-volume
          mountPath: /static
        - name: media-volume
          mountPath: /media
      volumes:
      - name: static-volume
        persistentVolumeClaim:
          claimName: static-pvc
      - name: media-volume
        persistentVolumeClaim:
          claimName: media-pvc
      imagePullSecrets:
        - name: dews-98-secret
---
apiVersion: v1
kind: Service
metadata:
  name: dews-nginx
  namespace: dews
  labels:
    service: dews-nginx
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    service: dews-nginx
  type: LoadBalancer
