migrations:
	python manage.py makemigrations

migrate:
	python manage.py migrate

flush:
	python manage.py flush

import:
	python manage.py importdata /dews/media/sat_data/archive/S1A_IW_GRDH_1SDV_20231116T053343_20231116T053408_051238_062E4B_84CA.SAFE.zip -m sentinel-1a