// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kDebugMode, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      if (kDebugMode) {
        return webDev;
      } else {
        return web;
      }
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcSE24sbt7GN6fVkY8QM5_lwg1ARNypHk',
    appId: '1:787983320297:web:a591ff3c09f37c8ae79c78',
    messagingSenderId: '787983320297',
    projectId: 'drought-ews-dev',
    authDomain: 'drought-ews-dev.firebaseapp.com',
    databaseURL: 'https://drought-ews-dev-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'drought-ews-dev.appspot.com',
  );

  static const FirebaseOptions webDev = FirebaseOptions(
    apiKey: 'AIzaSyAcSE24sbt7GN6fVkY8QM5_lwg1ARNypHk',
    appId: '1:787983320297:web:a591ff3c09f37c8ae79c78',
    messagingSenderId: '787983320297',
    projectId: 'drought-ews-dev',
    authDomain: 'drought-ews-dev.firebaseapp.com',
    databaseURL: 'http://127.0.0.1:9000/?ns=drought-ews-dev',
    storageBucket: 'drought-ews-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBduQHoWK_oV2ACpPQRCu9j4b8Eq7IXdCQ',
    appId: '1:787983320297:android:d4af40f534dfcf0de79c78',
    messagingSenderId: '787983320297',
    projectId: 'drought-ews-dev',
    databaseURL: 'https://drought-ews-dev-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'drought-ews-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC_ScfOmjBKPvbfS6sj1AzvUzJRPhFswM',
    appId: '1:787983320297:ios:21667fa4396942fce79c78',
    messagingSenderId: '787983320297',
    projectId: 'drought-ews-dev',
    databaseURL: 'https://drought-ews-dev-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'drought-ews-dev.appspot.com',
    iosBundleId: 'com.example.gui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC_ScfOmjBKPvbfS6sj1AzvUzJRPhFswM',
    appId: '1:787983320297:ios:e0eb69d5a54867e2e79c78',
    messagingSenderId: '787983320297',
    projectId: 'drought-ews-dev',
    databaseURL: 'https://drought-ews-dev-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'drought-ews-dev.appspot.com',
    iosBundleId: 'com.example.gui.RunnerTests',
  );
}
