// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return webDev;
  }

  /// Used for Docker environment
  static const FirebaseOptions webDev = FirebaseOptions(
    apiKey: 'fake-api-key',
    appId: 'app-id-123456789',
    messagingSenderId: 'messaging-sender-id-987654321',
    projectId: 'drought-ews-dev',
    authDomain: 'drought-ews-dev.firebaseapp.com',
    // databaseURL: 'http://127.0.0.1:9000/?ns=drought-ews-dev', // local
    databaseURL: 'http://172.19.0.3:9000/?ns=drought-ews-dev', // docker
    storageBucket: 'drought-ews-dev.appspot.com',
  );
}